import type { Metadata } from "next";
import { Aoboshi_One, Geist, Geist_Mono, Press_Start_2P, Wallpoet } from "next/font/google";
import "./globals.css";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // choose as needed
  variable: '--font-poppins', // Custom CSS variable
  display: 'swap',
});

const wallpoet = Wallpoet({
  subsets: ['latin'],
  weight: ['400'], // choose as needed
  variable: '--font-wallpoet', // Custom CSS variable
  display: 'swap',
});

const press_Start_2P = Press_Start_2P({
  subsets: ['latin'],
  weight: ['400'], // choose as needed
  variable: '--font-press_Start_2P', // Custom CSS variable
  display: 'swap',
});

const aoboshi_One = Aoboshi_One({
  subsets: ['latin'],
  weight: ['400'], // choose as needed
  variable: '--font-aoboshi_One', // Custom CSS variable
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${wallpoet.variable} ${press_Start_2P.variable}  ${aoboshi_One.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
